# Generated by Django 4.2.3 on 2023-07-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
